runtime: go115
env: standard

service: default

includes:
- secrets.yaml

handlers:

- url: /tasks/.+
  script: auto
  login: admin

- url: /_next
  static_dir: client/dest/_next

- url: /.*
  script: auto
