runtime: go121
env: standard

service: default

includes:
- secrets.yaml

handlers:

- url: /tasks/.+
  script: auto
  login: admin

- url: /assets
  static_dir: client/dest/assets

- url: /.*
  script: auto
