name: GAE Deploy PROD

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:

  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Test
      run: go test -v -cover -race

  js-test:
    name: JavaScript Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test
    - name: Export Test
      run: npm run export

  deploy:
    name: GAE Deploy PROD
    needs: [go-test, js-test]
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm ci
    - name: Export assets
      run: npm run export
    - name: Auth GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Recover App Secrets PROD
      run: 'echo "$APP_SECRETS_PROD_YAML" > secrets.yaml'
      shell: bash
      env:
        APP_SECRETS_PROD_YAML: ${{ secrets.APP_SECRETS_PROD_YAML }}
    - name: Deploy PROD
      run: gcloud app deploy ./app.yaml --quiet --no-cache
    - name: Deploy CRON
      run: gcloud app deploy ./cron.yaml --quiet --no-cache
    - name: Deploy Index
      run: gcloud datastore indexes create index.yaml --quiet
    - name: Announce on Slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
      run: |
        PREVIOUS_MERGE_COMMIT=$(git log --merges --max-count=1 --pretty="%H" --skip=1)
        echo "[INFO] PREVIOUS_MERGE_COMMIT  ${PREVIOUS_MERGE_COMMIT}"
        COMMITS_INCLUDED=$(git log --no-merges --pretty="・ %s" "${PREVIOUS_MERGE_COMMIT}..")
        echo "[INFO] COMMITS_INCLUDED ${COMMITS_INCLUDED}"
        PAYLOAD=$(jq -n \
          --arg channel "tech" \
          --arg commits "$COMMITS_INCLUDED" \
          --arg repo "$GITHUB_REPOSITORY" \
          --arg prev "$PREVIOUS_MERGE_COMMIT" \
          '{channel: $channel, text: ("あたらしいバージョンがリリースされました！ :tada:\n" + $commits + "\ngithub.com/" + $repo + "/compare/" + $prev + "..main")}')
        curl -XPOST \
          -d "$PAYLOAD" \
          -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" \
          -H "Content-Type: application/json" \
          https://slack.com/api/chat.postMessage
